server:
  port: 8080

spring:
  thymeleaf:
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/story_world?serverTimezone=UTC
    username: root
    password: smallhk
  jpa:
    hibernate:
      dll-auto: none
